config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :faculties, only: [:index, :new, :create, :destroy]
  root 'publicaciones#index', except: :show
  delete 'publicaciones/:id', to: 'publicaciones#destroy', as: :eliminar_publicacion
  patch "/publicaciones/:id", to: 'publicaciones#update'
  post '/publicaciones', to: 'publicaciones#create'
  get '/publicaciones/new', to: 'publicaciones#new', as: :nueva_publicacion
  get '/publicaciones', to: 'publicaciones#index'
  get '/publicaciones/:id', to: 'publicaciones#show', as: :publicacion
  get '/publicaciones/:id/edit', to: 'publicaciones#edit', as: :editar_publicacion
  get '/tendencias', to: 'publicaciones#tendencias'

  # config/routes.rb
  resources :reactions, only: [:index, :create]
  get '/reacciones', to: 'reactions#reacciones'


  resources :comments, only: [:create, :destroy]
  resources :responses, only: [:create, :destroy]

  resources :notifications, only: [:index]
  



  resources :users, only: [:show, :index], path: '/user', param: :username, as: :usuario
  delete '/user/:username', to: 'users#destroy', as: :eliminar_usuario

  
  namespace :authentication, path: '', as: '' do  
    resources :users, only: [:new, :create]
    resources :sessions, only: [:new, :create, :destroy]
    delete 'logout', to: 'sessions#destroy'

  end

end

app/controllers/publicaciones_controller.rb
class PublicacionesController < ApplicationController
    skip_before_action :protect_pages, only: [:index, :show]

    def index
      @categories=Category.all
      if !params[:category_id].present? 

      end

      @publicaciones = Publicacion.all.with_attached_imagen.order(created_at: :desc)
      @pagy, @publicaciones = pagy_countless(@publicaciones, items: 10)

      #como pueo agregar load asynkkc a eso
      if params[:category_id].present? 
        @publicaciones = Publicacion.all.with_attached_imagen.order(created_at: :desc)
        #@publicaciones = @publicaciones.joins(user: :faculty)
        @publicaciones=@publicaciones.where(category_id: params[:category_id])  
      

      end

      if params[:faculty_id].present?
        @faculty = Faculty.find_by(id: params[:faculty_id])
        @faculty_name = @faculty.name if @faculty.present?
        @publicaciones = Publicacion.all.with_attached_imagen.order(created_at: :desc)
        @publicaciones = @publicaciones.joins(:user).where(users: { faculty_id: params[:faculty_id] })
        @publicaciones_faculty = @publicaciones.joins(:user).where(users: { faculty_id: params[:faculty_id] })
      end




      
      if params[:query].present?
        @publicaciones = Publicacion.all.with_attached_imagen.order(created_at: :desc)
        @publicaciones = @publicaciones.search(params[:query])
      end
    end
    
    def show
     @publicacion= Publicacion.find(params[:id])
     @comments = @publicacion.comments.order(created_at: :desc)
     @respuestas=Response.all
     @me_divierte_count = @publicacion.reactions.where(reaction_type: 'me_divierte').count 
     @me_gusta_count = @publicacion.reactions.where(reaction_type: 'me_gusta').count 
     @me_encanta_count = @publicacion.reactions.where(reaction_type: 'me_encanta').count 
     @me_asombra_count = @publicacion.reactions.where(reaction_type: 'me_asombra').count 
     @me_entristese_count = @publicacion.reactions.where(reaction_type: 'me_entristese').count 
     @me_enoja_count= @publicacion.reactions.where(reaction_type: 'me_enoja').count 

    end
    
    def new
      @publicacion = Publicacion.new
    end
    
    def create
        @publicacion = Publicacion.new(publicacion_params)
        if @publicacion.save
          redirect_to publicaciones_path, notice: 'se subio tu publicacion'
        else
          render :new, status: :unprocessable_entity
        end
    end

    def edit
      autorizar! publicacion
      publicacion 
    end

    def tendencias
      # Obtener la fecha del lunes de esta semana
      fecha_lunes = Date.today.beginning_of_week(:monday)
      
      # Obtener la fecha del domingo de esta semana
      fecha_domingo = Date.today.end_of_week(:sunday)
      
      # Filtrar las publicaciones que se crearon entre el lunes y el domingo de esta semana
      @publicaciones = Publicacion.left_joins(:comments)
                                  .where(created_at: fecha_lunes.beginning_of_day..fecha_domingo.end_of_day)
                                  .group(:id)
                                  .order('COUNT(comments.id) DESC')
                                  .limit(5)
    end
    


    def update
      autorizar! publicacion
      if publicacion.update(publicacion_params)
        redirect_to publicaciones_path, notice: 'Tu publicaaacion se ha actualizado correctamente.'
      else 
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      autorizar! publicacion
      publicacion.destroy
      redirect_to publicaciones_path, notice: 'La publicación se ha eliminado correctamente.', status: :see_other

    end
    
    
      
    def publicacion
      @publicacion= Publicacion.find(params[:id])
    end
    
    private
    
    def publicacion_params
      params.require(:publicacion).permit(:titulo, :descripcion, :imagen, :category_id, :fijada, :fijadaindex)
    end
  end
    

app/views/publicaciones/_category.html.erb
<%= link_to publicaciones_path(category_id: category.id), class: "category-link" do %>
  <div class="category">
    <span class="category-name" style="color: white;"><%= category.name %></span>
    <span class="category-icon"><i class="fas fa-chevron-right"></i></span>
  </div>
<% end %>

<style>
  .category-link {
    text-decoration: none;
    color: #ffffff; /* Color del texto blanco */
    transition: color 0.3s ease; /* Transición suave al cambiar el color */
    cursor: pointer; /* Cambia el cursor al pasar por encima */
    outline: none; /* Elimina el contorno al hacer clic */
    display: block; /* Hace que todo el enlace sea clickeable */
  }

  .category-link:hover {
    color: #ffb400; /* Cambia el color del texto al pasar el mouse */
  }

  .category {
    padding: 10px;
    border-radius: 8px; /* Aumenta el radio de las esquinas del borde */
    margin-bottom: 10px; /* Espacio entre cada categoría */
    display: flex;
    justify-content: space-between;
    align-items: center;
    transition: background-color 0.3s ease; /* Añade transición al cambiar el color de fondo */
    background-color: #222; /* Fondo negro */
  }

  .category:hover {
    background-color: #333; /* Cambia el color de fondo al pasar el mouse */
  }

  .category-name {
    flex: 1;
    font-weight: bold; /* Hace el texto en negrita */
  }

  .category-icon {
    margin-left: 10px;
    opacity: 0;
    transition: opacity 0.3s ease; /* Añade transición a la opacidad */
  }

  .category:hover .category-icon {
    opacity: 1; /* Muestra el icono al pasar el mouse */
  }
</style>

app/views/publicaciones/edit.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Editar Publicación</title>
  <!-- Bootstrap CSS -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <div class="card-header bg-primary text-white">
            <h4 class="card-title text-center mb-0">Editar Publicación</h4>
          </div>
          <div class="card-body">
            <%= form_with model: @publicacion, html: { class: "form" } do |form| %>
              <% @publicacion.errors.full_messages.each do |error| %>
                <div class="alert alert-danger" role="alert">
                  <%= error %>
                </div>
              <% end %>
              
              <div class="form-group">
                <%= form.label :titulo, class: "font-weight-bold" %>
                <%= form.text_field :titulo, class: "form-control", placeholder: "Ingrese el título de la publicación" %>
              </div>

              <div class="form-group">
                <%= form.label :descripcion, class: "font-weight-bold" %>
                <%= form.text_area :descripcion, class: "form-control", placeholder: "Ingrese la descripción de la publicación" %>
              </div>

              <div class="form-group">
                <%= form.label :category_id, "Categoría", class: "font-weight-bold" %>
                <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name, { prompt: "Selecciona una categoría" }, class: "form-control" %>
              </div>

              <div class="form-group">
                <%= form.label :imagen, "Adjuntar imagen", class: "font-weight-bold" %>
                <%= form.file_field :imagen, class: "form-control-file" %>
              </div>

              <% if Current.user && Current.user.admin? %>
                <div class="form-group">
                  <%= form.label :fijada, "Fijar publicación por facultad", class: "font-weight-bold" %>
                  <%= form.check_box :fijada, class: "form-check-input" %>
                </div>
                <div class="form-group">
                  <%= form.label :fijada, "Fijar publicación en index", class: "font-weight-bold" %>
                  <%= form.check_box :fijadaindex, class: "form-check-input" %>
                </div>
              <% end %>

              <div class="form-group">
                <%= form.submit "Guardar cambios", class: "btn btn-primary btn-block" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap JS (opcional, si lo necesitas) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/publicaciones/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header bg-primary text-white">
          <h4 class="card-title text-center mb-0">Nueva Publicación</h4>
        </div>
        <div class="card-body">
          <%= form_with model: @publicacion, url: publicaciones_path, html: { class: "form" } do |form| %>
            <% @publicacion.errors.full_messages.each do |error| %>
              <div class="alert alert-danger" role="alert">
                <%= error %>
              </div>
            <% end %>
            
            <div class="form-group">
              <%= form.label :titulo, class: "font-weight-bold" %>
              <%= form.text_field :titulo, class: "form-control", placeholder: "Ingrese el título de la publicación" %>
            </div>

            <div class="form-group">
              <%= form.label :descripcion, class: "font-weight-bold" %>
              <%= form.text_area :descripcion, class: "form-control", placeholder: "Ingrese la descripción de la publicación" %>
            </div>

            <div class="form-group">
              <%= form.label :category_id, "Categoría", class: "font-weight-bold" %>
              <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name, { prompt: "Selecciona una categoría" }, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= form.label :imagen, "Adjuntar imagen", class: "font-weight-bold" %>
              <%= form.file_field :imagen, class: "form-control-file" %>
            </div>
            
            <% if (Current.user && Current.user.admin?) %>
              <div class="form-group">
              <%= form.label :fijada, "Fijar publicación en facultad", class: "font-weight-bold" %>
              <%= form.check_box :fijada, class: "form-check-input" %>
              </div>

              <div class="form-group">
              <%= form.label :fijadaindex, "Fijar publicación en index ", class: "font-weight-bold" %>
              <%= form.check_box :fijada, class: "form-check-input" %>
              </div>
            <%end%>

            <div class="form-group mb-0">
              <%= form.submit "Publicar", class: "btn btn-primary btn-block" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/publicaciones/show.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Red Social - Publicaciones</title>
  <!-- Bootstrap CSS -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  <!-- Font Awesome Icons -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
  <!-- Estilos personalizados -->
  <style>
    /* Estilos generales */
    body {
      background-color: #1f1f1f; /* Fondo oscuro */
      color: #fff; /* Texto blanco */
    }
    .card {
      background-color: #212E36; /* Fondo de las tarjetas */
      border: none;
      border-radius: 10px;
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.3);
    }
    .card-header {
      background-color: #343a40; /* Encabezado de tarjeta más oscuro */
      border-bottom: none;
      color: #fff; /* Texto blanco */
      display: flex;
      justify-content: center;
    }
    .card-header h1 {
      margin-bottom: 0;
      font-size: 1.5rem;
    }
    .card-body {
      background-color: #212E36; /* Cuerpo de tarjeta más oscuro */
    }
    .btn {
      background-color: #1f1f1f; /* Botones de color azul */
      border-color: #1f1f1f;
      color: #fff;
    }
    .btn:hover {
      background-color: #3685f3; /* Color de botón más oscuro al pasar el ratón */
      border-color: #3685f3;
    }
    .text-primary {
      color: #4dabf7 !important; /* Texto azul */
    }
    .text-muted {
      color: #999 !important; /* Texto gris */
    }

    /* Estilos específicos para las publicaciones */
    .publicacion {
      background-color: #272727; /* Fondo más oscuro para las publicaciones */
      border: none;
      border-radius: 10px;
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.3);
      transition: transform 0.3s ease;
    }
    .publicacion:hover {
      transform: translateY(-5px);
    }
    .publicacion img {
      max-width: 100%;
      border-radius: 10px 10px 0 0;
    }
    .publicacion h2 {
      margin-bottom: 5px;
      font-size: 1.5rem;
      color: #fff; /* Texto blanco */
    }
    .publicacion p {
      margin-bottom: 0;
      color: #999; /* Texto gris */
    }

    /* Estilos para los comentarios */
    .comentarios-container {
      background-color: #1f1f1f; /* Fondo oscuro */
      border-radius: 10px;
      padding: 10px;
      margin-top: 10px;
      max-height: 300px;
      overflow-y: auto;
    }
    .accordion-item {
      background-color: #343a40; /* Fondo de los elementos del acordeón */
      border: none;
      border-radius: 10px;
      margin-bottom: 10px;
    }
    .accordion-button {
      background-color: #4dabf7; /* Botones de color azul */
      border-color: #4dabf7;
      color: #fff;
    }
    .accordion-button:hover {
      background-color: #3685f3; /* Color de botón más oscuro al pasar el ratón */
      border-color: #3685f3;
    }
    .accordion-body {
      background-color: #272727; /* Fondo más oscuro para el cuerpo del acordeón */
      color: #999; /* Texto gris */
    }
    .response-form {
      margin-top: 10px;
    }
    .response-form .btn-primary {
      background-color: #4dabf7; /* Botones de color azul */
      border-color: #4dabf7;
    }
    .response-form .btn-primary:hover {
      background-color: #3685f3; /* Color de botón más oscuro al pasar el ratón */
      border-color: #3685f3;
    }
  </style>
</head>
<body>
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card shadow">
        <div class="card-header bg-primary text-white">
          <div class="username-container d-flex align-items-center">
            <i class="bi bi-person username-icon me-2"></i>
            <h1><%= @publicacion.user.username %></h1>
          </div>
        </div>
      
          <div class="card-body">
            <div class="text-center mb-4">
              <% if @publicacion.imagen.attached? %>
                <%= image_tag @publicacion.imagen, width: 400, class: "img-fluid rounded" %>
              <% end %>
            </div>
            <p class="lead text-center"><%= @publicacion.descripcion %></p>
            <p class="text-muted text-center mb-4"><i class="bi bi-calendar-check"></i><%= @publicacion.created_at.strftime("%d/%m/%Y %H:%M") %></p>

            <!-- contenedor para reaccionar -->
            <!-- MOSTRAR REAACCIONES DESTACADAS -->   
                <% destacadas = @publicacion.reactions.group(:reaction_type).count.sort_by { |_, v| -v }.first(3) %>
                <% if destacadas.present? %>
                  <div class="reacciones-destacadas">
                    <%= link_to reacciones_path(publicacion_id: @publicacion.id), data: { turbo_frame: '_top' } do %>
                      <% destacadas.each do |tipo, cantidad| %>
                        <%= "#{tipo.humanize.capitalize}" "#{cantidad}" if tipo.present?  %>
                      <% end %>
                      
                    <% end %>
                  </div>
                <% end %>
            

            <div class="d-flex justify-content-center mt-3">
              <% if @publicacion.user.id == session[:user_id] || (Current.user && Current.user.admin?) %>
                <%= link_to editar_publicacion_path(@publicacion), class: "btn btn-warning me-md-3 mb-2 mb-md-0", data: { turbo_frame: '_top' } do %>
                  <i class="bi bi-pencil-fill me-1"></i> Editar
                <% end %>
              <% end %>

              <% if @publicacion.user.id == session[:user_id] || (Current.user && Current.user.admin?) %>
                <%= link_to eliminar_publicacion_path(@publicacion), class: "btn btn-danger me-md-3 mb-2 mb-md-0", data: { turbo_method: :delete, turbo_confirm: '¿Estás seguro?' } do %>
                  <i class="bi bi-trash-fill me-1"></i> Eliminar
                <% end %>
              <% end %>

              <!-- Agregar más botones según sea necesario -->

              <% if @publicacion.user.id != session[:user_id] %>
                <%= link_to usuario_path(@publicacion.user.username), class: "btn btn-primary me-md-3 mb-2 mb-md-0" do %>
                  <i class="bi bi-person me-1"></i> Ver perfil 
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container mt-4">
    <%= turbo_frame_tag 'comentarios' do %>
      <h2 class="text-center mb-4">Comentarios(<%= @publicacion.comments.count %>)</h2>
      <div class="comentarios-container">
        <% @comments.order(created_at: :desc).each do |comment| %>
          <div class="card mb-3">
            <div class="card-body">
              <p class="card-text"><strong><%= comment.user.username %>:</strong> <%= comment.content %></p>
              <p class="card-text text-muted"><small><em>Publicado el <%= comment.created_at.strftime("%d de %B de %Y a las %H:%M") %></em></small></p>
              <!-- Desplegable para respuestas -->
              <div class="accordion" id="respuestasAccordion<%= comment.id %>">
                <div class="accordion-item">
                  <h2 class="accordion-header" id="headingRespuestas<%= comment.id %>">
                    <button class="accordion-button collapsed" type="button" data-toggle="collapse" data-target="#collapseRespuestas<%= comment.id %>" aria-expanded="false" aria-controls="collapseRespuestas<%= comment.id %>">
                      Ver Respuestas (<%= @respuestas.where(comment_id: comment.id).count %>)
                    </button>
                  </h2>
                  <div id="collapseRespuestas<%= comment.id %>" class="accordion-collapse collapse" aria-labelledby="headingRespuestas<%= comment.id %>" data-parent="#respuestasAccordion<%= comment.id %>">
                    <div class="accordion-body">
                      <!-- Contenedor de respuestas -->
                      <div class="respuestas-container">
                        <% @respuestas.where(comment_id: comment.id).order(created_at: :desc).each do |respuesta| %>
                          <span style="font-size: small;"> <%= respuesta.created_at.strftime("%d/%m/%Y %H:%M") %></span>
                          <p class="card-text"><strong><%= respuesta.user.username %>:</strong> <%= respuesta.content %></p>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <!-- Contenedor para escribir respuesta -->
              <div class="response-form mt-3">
                <%= form_with model: Response.new, url: responses_path(comment_id: comment.id), class: "response-form" , data: { turbo_frame: '_top' }  do |form| %>
                  <%= form.hidden_field :comment_id, value: comment.id %>
                  <%= form.hidden_field :user_id, value: session[:user_id] %>
                  <%= form.text_area :content, placeholder: "Escribe tu respuesta aquí...", class: "form-control mb-3" %>
                  <%= form.submit "Responder", class: "btn btn-primary" %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <%= form_with model: Comment.new, url: comments_path, class: "mt-4" , data: { turbo_frame: '_top' } do |form| %>
        <%= form.hidden_field :publicacion_id, value: @publicacion.id %>
        <%= form.hidden_field :user_id, value: session[:user_id] %>
        <%= form.text_area :content, placeholder: "Escribe tu comentario aquí...", class: "form-control mb-3" %>
        <%= form.submit "Comentar", class: "btn btn-primary" %>
      <% end %>
    <%end%>
  </div>

  <!-- Bootstrap JS (opcional, si lo necesitas) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <!-- Script para el funcionamiento de los desplegables -->
  <script>
    $(document).ready(function() {
      $('.accordion-button').click(function() {
        $(this).toggleClass('collapsed');
      });
    });
  </script>
</body>
</html>

app/views/publicaciones/tendencias.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Publicaciones</title>
  <!-- Bootstrap CSS -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
  <style>
    body {
      font-family: 'Roboto', sans-serif;
      background-color: #f8f9fa;
    }
    .container {
      max-width: 800px;
    }
    .card {
      border: none;
      box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.1);
      transition: transform 0.3s ease;
    }
    .card:hover {
      transform: translateY(-5px);
    }
    .card-title {
      color: #333;
    }
    .usuario {
      color: #666;
    }
    .card-link {
      text-decoration: none;
      color: inherit;
    }
    .card-link:hover {
      text-decoration: none;
      color: inherit;
    }
    .placeholder-image {
      height: 200px;
      background-color: #ddd;
    }
  </style>
</head>
<body>

<div class="container mt-5">
  <h2 class="text-center mb-4" style="color: #333;">Publicaciones Top 5 en tendencia semanal</h2>
  <div class="row">
    <% @publicaciones.each do |publicacion| %>
      <div class="col-md-6 mb-4">
        <div class="card">
          <!-- Contenido de la publicación -->
          <%= link_to publicacion_path(publicacion.id), class: "card-link", data: { turbo_frame: '_top' } do %>
            <% if publicacion.imagen.attached? %>
              <%= image_tag publicacion.imagen, class: "card-img-top", alt: "Imagen de la publicación" %>
            <% else %>
              <div class="placeholder-image card-img-top"></div>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= publicacion.titulo %></h5>
              <!-- Contenedor del nombre de usuario -->
              <div class="usuario mb-3">
                <i class="bi bi-person me-2" style="font-size: 20px;"></i>
                <strong><%= link_to "#{publicacion.user.username} - #{publicacion.user.faculty.name}", usuario_path(publicacion.user.username), data: { turbo_frame: '_top' } %></strong>
              </div>
              <!-- Otros detalles de la publicación -->
              <%#<p class="card-text"><strong>Comentarios:</strong> <%= publicacion.comments.count %>
              <p class="card-text"><small class="text-muted"><i class="far fa-calendar-alt me-1"></i><%= publicacion.created_at.strftime("%d/%m/%Y %H:%M") %></small></p>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!-- Bootstrap JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>