config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :faculties, only: [:index, :new, :create, :destroy]
  root 'publicaciones#index', except: :show
  delete 'publicaciones/:id', to: 'publicaciones#destroy', as: :eliminar_publicacion
  patch "/publicaciones/:id", to: 'publicaciones#update'
  post '/publicaciones', to: 'publicaciones#create'
  get '/publicaciones/new', to: 'publicaciones#new', as: :nueva_publicacion
  get '/publicaciones', to: 'publicaciones#index'
  get '/publicaciones/:id', to: 'publicaciones#show', as: :publicacion
  get '/publicaciones/:id/edit', to: 'publicaciones#edit', as: :editar_publicacion
  get '/tendencias', to: 'publicaciones#tendencias'

  # config/routes.rb
  resources :reactions, only: [:index, :create]
  get '/reacciones', to: 'reactions#reacciones'


  resources :comments, only: [:create, :destroy]
  resources :responses, only: [:create, :destroy]

  resources :notifications, only: [:index]
  



  resources :users, only: [:show, :index], path: '/user', param: :username, as: :usuario
  delete '/user/:username', to: 'users#destroy', as: :eliminar_usuario

  
  namespace :authentication, path: '', as: '' do  
    resources :users, only: [:new, :create]
    resources :sessions, only: [:new, :create, :destroy]
    delete 'logout', to: 'sessions#destroy'

  end

end

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
    <div class="flash <%= type %>">
      <%= message %>
    </div>
<% end %>
  

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <!-- Marca del Navbar -->
    <%= link_to(publicaciones_path, class: "navbar-brand") do %>
      <h1 class="m-0">forUNAS</h1>
    <% end %>
    
    <!-- Botón de desplegar en dispositivos pequeños -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <!-- Contenido del Navbar -->
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        
        <!-- Enlace a la página de perfil del usuario actual -->
        <% if session[:user_id].present? && User.exists?(session[:user_id]) %>
          <li class="nav-item">
            <%= link_to(usuario_path(User.find(session[:user_id]).username), class: "nav-link") do %>
              <i class="bi bi-person"></i><%= User.find_by(id: session[:user_id]).username %>
            <% end %>
          </li>
        <% end %>
        
        <!-- Enlace para crear una nueva publicación -->
        <% if Current.user %>
          <li class="nav-item">
            <%= link_to('Nueva publicación', nueva_publicacion_path, class: "nav-link") %>
          </li>
        <% end %>
        
        <!-- Enlace a la página de notificaciones -->
        <% if session[:user_id].present? && User.exists?(session[:user_id]) %>
          <% unread_notifications = Current.user.notifications.where(read: false) %>
          <li class="nav-item">
            <%= link_to notifications_path, class: "nav-link" do %>
              <i class="bi bi-bell"></i>
              <span style="color: red;"><%= unread_notifications.count %></span>
            <% end %>
          </li>
        <% end %>

        <!-- Menú desplegable para el usuario administrador -->
        <% if Current.user && Current.user.admin? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Administrador
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to('Categorías', categories_path, class: "dropdown-item") %>
              <!-- Puedes agregar más opciones aquí si es necesario -->
              <%= link_to('Facultades', faculties_path, class: "dropdown-item") %>
            </div>
          </li>
        <% end %>
        
        <!-- Enlace para cerrar sesión -->
        <% if Current.user %>
          <li class="nav-item">
            <%= link_to('Cerrar sesión', session_path(1), class: "nav-link", data: { turbo_method: :delete, turbo_confirm: '¿Estás seguro?' }) %>
          </li>
        <% end %>
        
        <!-- Enlaces para iniciar sesión y registrarse -->
        <% if User.none? || Current.user.nil? %>
          <li class="nav-item">
            <%= link_to('Iniciar sesión', new_session_path, class: "nav-link") %>
          </li>
          <li class="nav-item">
            <%= link_to('Registrarse', new_user_path, class: "nav-link") %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>