config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :faculties, only: [:index, :new, :create, :destroy]
  root 'publicaciones#index', except: :show
  delete 'publicaciones/:id', to: 'publicaciones#destroy', as: :eliminar_publicacion
  patch "/publicaciones/:id", to: 'publicaciones#update'
  post '/publicaciones', to: 'publicaciones#create'
  get '/publicaciones/new', to: 'publicaciones#new', as: :nueva_publicacion
  get '/publicaciones', to: 'publicaciones#index'
  get '/publicaciones/:id', to: 'publicaciones#show', as: :publicacion
  get '/publicaciones/:id/edit', to: 'publicaciones#edit', as: :editar_publicacion
  get '/tendencias', to: 'publicaciones#tendencias'

  # config/routes.rb
  resources :reactions, only: [:index, :create]
  get '/reacciones', to: 'reactions#reacciones'


  resources :comments, only: [:create, :destroy]
  resources :responses, only: [:create, :destroy]

  resources :notifications, only: [:index]
  



  resources :users, only: [:show, :index], path: '/user', param: :username, as: :usuario
  delete '/user/:username', to: 'users#destroy', as: :eliminar_usuario

  
  namespace :authentication, path: '', as: '' do  
    resources :users, only: [:new, :create]
    resources :sessions, only: [:new, :create, :destroy]
    delete 'logout', to: 'sessions#destroy'

  end

end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, uniqueness: true

    has_many :publicacions, dependent: :restrict_with_exception
    
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  

  # GET /categories or /categories.json
  def index
    @categories = Category.all.order(name: :asc).load_async
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    
    if @category.save
     redirect_to categories_url, notice: "creado"
    else
      flash.now[:alert] = "No se pudo crear la categoría. Por favor, verifica que el nombre no esté vacío y no sea el mismo que otro."
      render :new, status: :unprocessable_entity
    end
    
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    if category.update(category_params)
      redirect_to categories_url, notice: "Category was successfully updated." 
    else
      render :edit, status: :unprocessable_entity     
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    category.destroy!.load_async

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def category
      @category = Category.find(params[:id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">

  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>
  <%= link_to 'editar', edit_category_path(category) %>
  <%= link_to 'eliminar categoria', category_path(category), data: {turbo_method: :delete, turbo_confirm: 'Estas seguro?'} %>

</div>

<table class="table table-hover">
    <thead>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  
  <%= @category.errors.full_messages.each do |error| %>
    <div>
      <%= error %>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>


<div id="categories">
  
  <% @categories.each do |category| %>
    <%= render category %>
  <% end %>
</div>


<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>